using UnityEngine;
using System.Collections;

public class Hidden : MonoBehaviour
{
    public Caught player;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void OnTriggerEnter2D(Collider2D collider){
        if(collider.gameObject.CompareTag("Player")){
        player.hidden = true;
        }
    }

    public void OnTriggerExit2D(Collider2D collider){
        if(collider.gameObject.CompareTag("Player")){
            player.hidden = false;
        }
    }
}